version: '2'

services:
  mysql:
    image: mysql:5.7.36
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_DATABASE=validation_source
      - MYSQL_USER=data_validation_user
      - MYSQL_PASSWORD=data_validation_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:14.1
    container_name: postgres
    environment:
      - "TZ=Europe/Amsterdam"
      - "POSTGRES_USER=data_validation_user"
      - "POSTGRES_PASSWORD=data_validation_pass"
#      - POSTGRES_DB=validation_target
    ports:
      - "5432:5432"
    volumes:
      - postgress_data:/var/lib/postgresql/data
#    volumes:
#      - "./sql:/docker-entrypoint-initdb.d"

volumes:
  mysql_data:
  postgress_data:
